apiVersion: v1
kind: Service
metadata:
  name: engine
  labels:
    app: engine
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: http
  selector:
    app: engine
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine
spec:
  selector:
    matchLabels:
      app: engine
  replicas: 2
  template:
    metadata:
      labels:
        app: engine
    spec:
      containers:
      - name: engine
        image: chess.azurecr.io/engine
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
